export default {

    PURPLE: '#985bd9',
    BLUE_DEFAULT: '#20939e',

    // General
    GRAY_BACKGROUND: '#F2F3F4',
    WHITE_BACKGROUND: '#FFF',
    DEEP_GRAY_BACKGROUND: '#383A3C',
    GRAY_GRAY_BACKGROUND: '#A2A2A2',
    PRIMARY: '#C4EE68',
    PRIMARY_TEXT: '#FFF',
    GRAY_TEXT: '#A2A2A2',
    SOFT_GRAY_TEXT: '#B9B9B9',
    DEEP_GRAY_TEXT: '#383A3C',
    WHITE_TWO_BACKGROUND: '#F2F3F4',
    HARD_GRAY: '#4B4D4E',
    MEDIUM_GRAY: '#545758',
    LOW_GRAY: '#676767',
    RED_HEART: '#D50F08',
    OVERLAY_BACKGROUND: 'rgba(0, 0, 0, 0.85)',
    YELLOW_STAR: '#FFCC00',
    BLACK_TEXT: '#000',

    // Avatar
    AVATAR_TITLE_TEXT_COLOR: '#000',
    AVATAR_SUBTITLE_TEXT_COLOR: '#A2A2A2',
    AVATAR_ARROW_COLOR: '#C4EE68',
    AVATAR_ARROW_BACKGROUND: '#000',
    AVATAR_DEFAULT_BACKGROUND: '#FFF',
    AVATAR_GRAY_BACKGROUND: '#F2F3F4',

    // MainHeader
    PRIMARY_HEADER_BACKGROUND: '#FFF',
    PRIMARY_HEADER_TEXT_COLOR: '#000',

    // Menu
    MENU_BACKGROUND: '#F2F3F4',
    MENU_TEXT_COLOR: '#000',
    MENU_ICONS_COLOR: '#A2A2A2',
    MENU_SEPARATOR_COLOR: '#A2A2A2',

    // Footer button
    FOOTER_BUTTON_ACTIVE_BACKGROUND: '#383A3C',
    FOOTER_BUTTON_INACTIVE_BACKGROUND: '#FFF',
    FOOTER_BUTTON_INACTIVE_COLOR: '#A2A2A2',
    FOOTER_BUTTON_ACTIVE_COLOR: '#C4EE68',

    // Buttons
    PRIMARY_BUTTON_TEXT_COLOR: '#C4EE68',
    PRIMARY_BUTTON_BACKGROUND_COLOR: '#C4EE68',
    WHITE_BUTTON_TEXT_COLOR: '#FFF',
    SECONDARY_BUTTON_TEXT_COLOR: '#383A3C',
    BLACK_BUTTON_COLOR: '#383A3C',
    GRAY_BUTTON_COLOR: '#3E4043',

    // Inputs
    PRIMARY_INPUT_TEXT_COLOR: '#FFF',
    PRIMARY_INPUT_COLOR: '#C4EE68',
    BLACK_INPUT_COLOR: '#383A3C',
    GRAY_INPUT_COLOR: '#3E4043',

    // Calendar
    CALENDAR_PRIMARY_TEXT_COLOR: '#383A3C',
    CALENDAR_ARROW_COLOR: '#383A3C',
    CALENDAR_SELECTED_TEXT_COLOR: '#FFF',
    CALENDAR_SELECTED_BACKGROUNDCOLOR: '#C4EE68',
    CALENDAR_DISABLED_TEXT_COLOR: '#D2D7DC',
    CALENDAR_SELECTED_COLOR: '#C4EE68',

    // DisplayCard
    DISPLAYCARD_BACKGROUNDCOLOR: '#383A3C',
    DISPLAYCARD_TITLE_TEXT_COLOR: '#F1F1F1',
    DISPLAYCARD_SUBTITLE_TEXT_COLOR: '#B6B6B6',
    DISPLAYCARD_CALLOUT_COLOR: '#C4EE68',

    // TIMECALLOUT
    TIME_CALLOUT_CALLOUT_BORDER_COLOR: '#C4EE68',
    TIME_CALLOUT_BACKGROUNDCOLOR_DEFAULT: '#FFF',
    TIME_CALLOUT_PRIMARY_TEXT_COLOR: '#383A3C',
    TIME_CALLOUT_SECONDARY_TEXT_COLOR: '#D2D7DC',
    TIME_CALLOUT_PRIMARY_BUTTON_TEXT_COLOR: '#383A3C',
    TIME_CALLOUT_SECONDARY_BUTTON_TEXT_COLOR: '#FFD8D8',

};
